### ISSUE TITLE
Upgrade BCEL version to support Java 8 lambdas

### ISSUE THREAD

**Issue by bumfo** [robo-code/codesize#3]
BCEL 5.2 does not support some java 6, 7, 8 features, such as Lambdas. Please consider upgrade BCEL Version.

**Comment by flemming-n-larsen** [comment]
Version 1.2 has been upgraded for BCEL 6.2, which supports Java 6, 7, 8, and 9 experimental.
I am currently awaiting approval with Sonatype to upload a the new version of Codesize to the Maven Repository.

**Comment by flemming-n-larsen** [comment]
Codesize is now available on the Maven Repository as version 1.2:
https://mvnrepository.com/artifact/net.sf.robocode/codesize/1.2

Robocode 1.9.3.4 will make use of Codesize 1.2
